### ISSUE TITLE
Dragging open file tab sometime crashes

### ISSUE THREAD

**Issue by jalshukaili2016** [DReynolds4001/SftwrEngMissionControl#21]
Description of the Issue
When trying to drag the open file tab to reorder and change its position among other tabs
sometimes NPP clones the dragged tab with weird name in chinese symbols.
The original tab stays in the same place.
After that happens, it's impossible to close NPP.
File->Exit doesn't work.
Closing window with X in top right corner doesn't work.
The cloned tab with weird name doesn't display tooltip with full path.
It's impossible to close the cloned tab, trying to close it closes the adjacent tab and only 1 time.

Steps to Reproduce the Issue
*** 1. I'm working with NppFTP on php, css and js files.
*** 2. Usually have 10 or more open tabs.
*** 3. Can be working for 2 days before crash. (Computer is turned ON always).
*** I open and close tabs alot, editing different files on 2-3 ftps, switching between them.
*** after trying to reproduce the bug, these steps are not necessary.

Just open Notepad with a previous session, having many tabs open.
Drag any open file tab or try closing some tabs first, and then drag.
Also sometime tabs move erroneously, unpredictable. Hard to move the tab into correct place.
Expected Behavior
The tab should just move to new position

Actual Behavior
The tab cloned itself, the original tab stayed in same place.

**Comment by khalifa1334** [comment]
#6082
