### ISSUE TITLE
Edit windows scrolled after restore from minimize

### ISSUE THREAD

**Issue by jalshukaili2016** [DReynolds4001/SftwrEngMissionControl#26]
Description of the Issue
Minimizing and then restoring Notepad++, the edit windows have been scrolled down by several lines (one screenful?).

After repeated minimize/restore cycles this eventually results in all the edit windows being at the bottom of the text buffers.

This behavior does not appear to affect the location of the insertion caret.

Steps to Reproduce the Issue
Have one or more files open in NP++
Minimize the application.
Restore the application.
Observe the edit windows have scrolled down some number of lines.

Expected Behavior
The edit windows should remain in the same scroll location after a restore.

Actual Behavior
The edit windows have scrolled down some number of lines.

**Comment by khalifa1334** [comment]
#5258
